# Generated by Django 4.2.7 on 2026-02-01 22:05

import apps.audio_data.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("languages", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("text_data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpeakerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("speaker_id", models.CharField(max_length=50, unique=True)),
                (
                    "age_range",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("18-25", "18-25"),
                            ("26-35", "26-35"),
                            ("36-45", "36-45"),
                            ("46-55", "46-55"),
                            ("56-65", "56-65"),
                            ("65+", "65+"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                            ("prefer_not_to_say", "Prefer not to say"),
                        ],
                        max_length=20,
                    ),
                ),
                ("total_recordings", models.PositiveIntegerField(default=0)),
                ("total_duration", models.FloatField(default=0.0)),
                ("average_quality", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fluent_languages",
                    models.ManyToManyField(
                        related_name="fluent_speakers_audio", to="languages.language"
                    ),
                ),
                (
                    "native_languages",
                    models.ManyToManyField(
                        related_name="native_speakers_audio", to="languages.language"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speaker_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AudioRecording",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(
                        upload_to=apps.audio_data.models.audio_upload_path
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "file_size",
                    models.PositiveIntegerField(help_text="File size in bytes"),
                ),
                (
                    "duration",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.1),
                            django.core.validators.MaxValueValidator(30.0),
                        ]
                    ),
                ),
                ("sample_rate", models.PositiveIntegerField(default=16000)),
                ("channels", models.PositiveIntegerField(default=1)),
                ("bit_depth", models.PositiveIntegerField(default=16)),
                ("transcript", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("processing", "Processing"),
                            ("processed", "Processed"),
                            ("validated", "Validated"),
                            ("rejected", "Rejected"),
                            ("error", "Error"),
                        ],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                (
                    "recording_type",
                    models.CharField(
                        choices=[
                            ("read_speech", "Read Speech"),
                            ("spontaneous", "Spontaneous Speech"),
                            ("conversation", "Conversation"),
                            ("narration", "Narration"),
                        ],
                        default="read_speech",
                        max_length=20,
                    ),
                ),
                ("signal_to_noise_ratio", models.FloatField(blank=True, null=True)),
                ("silence_ratio", models.FloatField(blank=True, null=True)),
                ("clipping_detected", models.BooleanField(default=False)),
                (
                    "quality_score",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("speaker_id", models.CharField(blank=True, max_length=50)),
                (
                    "speaker_age_range",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("18-25", "18-25"),
                            ("26-35", "26-35"),
                            ("36-45", "36-45"),
                            ("46-55", "46-55"),
                            ("56-65", "56-65"),
                            ("65+", "65+"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "speaker_gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                            ("prefer_not_to_say", "Prefer not to say"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="languages.language",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audio_recordings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sentence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audio_recordings",
                        to="text_data.sentence",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AudioProcessingResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "processing_duration",
                    models.FloatField(help_text="Processing time in seconds"),
                ),
                ("spectral_features", models.JSONField(blank=True, default=dict)),
                ("mfcc_features", models.JSONField(blank=True, default=dict)),
                ("pitch_features", models.JSONField(blank=True, default=dict)),
                ("noise_level", models.FloatField(blank=True, null=True)),
                ("speech_segments", models.JSONField(blank=True, default=list)),
                ("silence_segments", models.JSONField(blank=True, default=list)),
                ("auto_transcript", models.TextField(blank=True)),
                ("transcript_confidence", models.FloatField(blank=True, null=True)),
                ("processing_errors", models.JSONField(blank=True, default=list)),
                (
                    "recording",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_result",
                        to="audio_data.audiorecording",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AudioDataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "dataset_type",
                    models.CharField(
                        choices=[
                            ("asr", "Automatic Speech Recognition"),
                            ("speech_translation", "Speech Translation"),
                            ("speaker_id", "Speaker Identification"),
                            ("emotion", "Emotion Recognition"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_public", models.BooleanField(default=True)),
                ("version", models.CharField(default="1.0", max_length=20)),
                ("license", models.CharField(default="CC-BY-4.0", max_length=50)),
                ("total_duration", models.FloatField(default=0.0)),
                ("recording_count", models.PositiveIntegerField(default=0)),
                ("speaker_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="languages.language",
                    ),
                ),
                (
                    "recordings",
                    models.ManyToManyField(
                        related_name="datasets", to="audio_data.audiorecording"
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="audiorecording",
            index=models.Index(
                fields=["language", "status"], name="audio_data__languag_1a0138_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="audiorecording",
            index=models.Index(
                fields=["recorded_by"], name="audio_data__recorde_732a4d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="audiorecording",
            index=models.Index(
                fields=["sentence"], name="audio_data__sentenc_571271_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="audiodataset",
            unique_together={("name", "version")},
        ),
    ]
