# Generated by Django 4.2.7 on 2026-02-01 22:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("languages", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Corpus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "corpus_type",
                    models.CharField(
                        choices=[
                            ("general", "General Domain"),
                            ("news", "News"),
                            ("literature", "Literature"),
                            ("religious", "Religious Texts"),
                            ("educational", "Educational"),
                            ("conversational", "Conversational"),
                            ("technical", "Technical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_public", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sentence_count", models.PositiveIntegerField(default=0)),
                ("word_count", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="languages.language",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "corpora",
            },
        ),
        migrations.CreateModel(
            name="Sentence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        validators=[
                            django.core.validators.MinLengthValidator(1),
                            django.core.validators.MaxLengthValidator(1000),
                        ]
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("validated", "Validated"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="intermediate",
                        max_length=20,
                    ),
                ),
                (
                    "source_text",
                    models.TextField(
                        blank=True, help_text="Original text if this is a translation"
                    ),
                ),
                ("word_count", models.PositiveIntegerField(default=0)),
                ("character_count", models.PositiveIntegerField(default=0)),
                ("confidence_score", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contributed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributed_sentences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "corpus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sentences",
                        to="text_data.corpus",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="languages.language",
                    ),
                ),
                (
                    "source_language",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_sentences",
                        to="languages.language",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SentenceMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pos_tags", models.JSONField(blank=True, default=list)),
                ("named_entities", models.JSONField(blank=True, default=list)),
                ("syntactic_features", models.JSONField(blank=True, default=dict)),
                ("cultural_notes", models.TextField(blank=True)),
                (
                    "usage_context",
                    models.CharField(
                        choices=[
                            ("formal", "Formal"),
                            ("informal", "Informal"),
                            ("ceremonial", "Ceremonial"),
                            ("everyday", "Everyday"),
                        ],
                        default="everyday",
                        max_length=50,
                    ),
                ),
                ("has_audio", models.BooleanField(default=False)),
                ("audio_duration", models.FloatField(blank=True, null=True)),
                (
                    "sentence",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata",
                        to="text_data.sentence",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("validated", "Validated"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "translation_type",
                    models.CharField(
                        choices=[
                            ("literal", "Literal"),
                            ("free", "Free"),
                            ("cultural", "Cultural Adaptation"),
                        ],
                        default="free",
                        max_length=20,
                    ),
                ),
                ("confidence_score", models.FloatField(default=0.0)),
                ("length_ratio", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_sentence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations_as_source",
                        to="text_data.sentence",
                    ),
                ),
                (
                    "target_sentence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations_as_target",
                        to="text_data.sentence",
                    ),
                ),
                (
                    "translated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["source_sentence", "status"],
                        name="text_data_t_source__ef6020_idx",
                    ),
                    models.Index(
                        fields=["target_sentence", "status"],
                        name="text_data_t_target__353027_idx",
                    ),
                ],
                "unique_together": {("source_sentence", "target_sentence")},
            },
        ),
        migrations.AddIndex(
            model_name="sentence",
            index=models.Index(
                fields=["language", "status"], name="text_data_s_languag_f3cfcb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sentence",
            index=models.Index(
                fields=["corpus", "status"], name="text_data_s_corpus__f217bf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sentence",
            index=models.Index(
                fields=["contributed_by"], name="text_data_s_contrib_45d399_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="corpus",
            unique_together={("name", "language")},
        ),
    ]
