# Generated by Django 4.2.7 on 2026-02-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("contributor", "Contributor"),
                    ("reviewer", "Reviewer"),
                    ("language_lead", "Language Lead"),
                    ("admin", "Admin"),
                    ("superuser", "Super User"),
                ],
                default="contributor",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
