# Generated by Django 4.2.7 on 2026-02-01 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "iso_code",
                    models.CharField(blank=True, max_length=10, null=True, unique=True),
                ),
                (
                    "family",
                    models.CharField(
                        choices=[
                            ("mande", "Mande"),
                            ("kru", "Kru"),
                            ("mel", "Mel"),
                            ("niger_congo", "Niger-Congo"),
                            ("creole", "Creole"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
                (
                    "regions",
                    models.TextField(help_text="Comma-separated list of regions"),
                ),
                (
                    "estimated_speakers",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "endangerment_level",
                    models.CharField(
                        choices=[
                            ("safe", "Safe"),
                            ("vulnerable", "Vulnerable"),
                            ("definitely_endangered", "Definitely Endangered"),
                            ("severely_endangered", "Severely Endangered"),
                            ("critically_endangered", "Critically Endangered"),
                            ("extinct", "Extinct"),
                        ],
                        default="safe",
                        max_length=25,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Script",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("unicode_range", models.CharField(blank=True, max_length=100)),
                (
                    "direction",
                    models.CharField(
                        choices=[("ltr", "Left-to-Right"), ("rtl", "Right-to-Left")],
                        default="ltr",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Orthography",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_official", models.BooleanField(default=False)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "alphabet",
                    models.TextField(help_text="Characters used in this orthography"),
                ),
                ("tone_marking", models.BooleanField(default=False)),
                ("tone_system", models.TextField(blank=True)),
                (
                    "character_set",
                    models.TextField(
                        blank=True, help_text="Allowed characters (regex)"
                    ),
                ),
                ("normalization_rules", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orthographies",
                        to="languages.language",
                    ),
                ),
                (
                    "script",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="languages.script",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_primary", "-is_official", "name"],
                "unique_together": {("language", "name")},
            },
        ),
        migrations.CreateModel(
            name="LanguageVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("region", models.CharField(max_length=100)),
                ("is_standard", models.BooleanField(default=False)),
                ("phonological_notes", models.TextField(blank=True)),
                ("lexical_notes", models.TextField(blank=True)),
                ("grammatical_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="languages.language",
                    ),
                ),
            ],
            options={
                "unique_together": {("language", "name")},
            },
        ),
        migrations.CreateModel(
            name="LanguagePair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("priority", models.PositiveIntegerField(default=1)),
                ("sentence_count", models.PositiveIntegerField(default=0)),
                ("validated_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_pairs",
                        to="languages.language",
                    ),
                ),
                (
                    "target_language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_pairs",
                        to="languages.language",
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "source_language__name"],
                "unique_together": {("source_language", "target_language")},
            },
        ),
    ]
