# Generated by Django 4.2.7 on 2026-02-03 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("languages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AudioData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("file_path", models.CharField(max_length=500)),
                ("duration", models.IntegerField(blank=True, null=True)),
                (
                    "speaker_gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("speaker_age_range", models.CharField(blank=True, max_length=20)),
                ("quality_score", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contributor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TextData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_text", models.TextField()),
                ("target_text", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contributor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="languagevariant",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="languagevariant",
            name="language",
        ),
        migrations.AlterUniqueTogether(
            name="orthography",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="orthography",
            name="language",
        ),
        migrations.RemoveField(
            model_name="orthography",
            name="script",
        ),
        migrations.AlterField(
            model_name="language",
            name="estimated_speakers",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="language",
            name="family",
            field=models.CharField(
                choices=[
                    ("niger_congo", "Niger-Congo"),
                    ("mande", "Mande"),
                    ("kru", "Kru"),
                    ("atlantic", "Atlantic"),
                    ("other", "Other"),
                ],
                default="niger_congo",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="iso_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="language",
            name="regions",
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name="LanguagePair",
        ),
        migrations.DeleteModel(
            name="LanguageVariant",
        ),
        migrations.DeleteModel(
            name="Orthography",
        ),
        migrations.DeleteModel(
            name="Script",
        ),
        migrations.AddField(
            model_name="textdata",
            name="source_language",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="source_texts",
                to="languages.language",
            ),
        ),
        migrations.AddField(
            model_name="textdata",
            name="target_language",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="target_texts",
                to="languages.language",
            ),
        ),
        migrations.AddField(
            model_name="audiodata",
            name="language",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="languages.language"
            ),
        ),
    ]
